### ISSUE TITLE
Issue about the additional datasets required

### ISSUE THREAD

**Issue by engrubaid** [cbur24/NEE_modelling#1]
hello, 

I am running the notebooks and downloaded the datasets required but there are some additional datasets required. can you please help me about these datasets, where can i get it. The additional datasets are the covariables listed down.

covariables=[
                                 #'LAI',
                                 #'LAI_anom',
                                 'kNDVI',
                                 'kNDVI_anom',
                                 #'FPAR',
                                 #'FPAR-NDVI',
                                 'LST',
                                 'trees',
                                 'grass',
                                 'bare',
                                 'C4_grass',
                                 #'Tree',
                                 #'NonTree',
                                 #'NonVeg',
                                 'LST_Tair',
                                 'TWI',
                                 'NDWI',
                                 #'NDWI_anom',
                                 'rain',
                                 #'rain_cml3',
                                 #'rain_cml6',
                                 #'rain_cml12',
                                 'rain_anom',
                                 'rain_cml3_anom',
                                 'rain_cml6_anom',
                                 'rain_cml12_anom',
                                 'srad',
                                 'srad_anom',
                                 'vpd',
                                 'tavg',
                                 'tavg_anom',
                                 'SOC',
                                 #'CO2',
                                 #'C4percent',
                                 #'Elevation',
                                 #'MOY',
                                 'VegH',
                                 #'MI'
                            ],

Where i can download the data in "/g/data/os22/chad_tmp/NEE_modelling/data" the given directory?

Thanks in advance 

Best Regards
Ubaid Akbar

**Comment by cbur24** [comment]
@engrubaid this repository exist as a reference for the _research_ methods described in this [EGU paper](https://bg.copernicus.org/articles/20/4109/2023/), you will not be able to simply clone the repo and build the same product. 

If you wish to build a similar dataset, you are welcome to use the code in the notebooks as inspiration, but you'll need to do the hard work of assembling covariables, and a working python environment, yourself.

**Comment by engrubaid** [comment]
it means i need assemble all the covariables and create all the covariable files as included.

Thank you very much for your reply
